#pragma once

// Golden byte payloads + expected decode results, generated by actually running radar_4d_cli.py's
// RadarCANFDParser logic offline (via a standalone copy with `import can` stripped out, since
// python-can isn't required just to exercise the pure bit-math) against these exact byte arrays.
// See the scratch generator script referenced in the Phase 3 checkpoint notes if these ever need
// regenerating -- do not hand-edit the byte arrays or expected values independently of that script.

#include <cstdint>
#include <vector>

namespace bev {
namespace radarcam {
namespace test_fixtures {

// v1: typical stationary reflector return, no sign bits set, az/el both land exactly on 0.
inline const std::vector<uint8_t> kSlotV1TypicalStationary = {0, 0, 0, 250, 0, 2, 8, 160, 0, 140, 160,
    0, 2, 50, 128, 0, 20, 20, 0};
// Expected: range_m=5.0 vel_mps=0.0 azimuth_rad=0.0 elevation_rad=0.0 rcs_dbsm=0.0 snr_db=5.0
//           is_stationary=true, position=(5.0, 0.0, 0.0)

// v2: azimuth/elevation raw values have the sign bit set (_s16 conversion path exercised).
inline const std::vector<uint8_t> kSlotV2SignBitSet = {0, 0, 2, 105, 0, 1, 56, 128, 1, 56, 128, 0, 6,
    26, 128, 0, 31, 201, 0};
// Expected: range_m=12.34 vel_mps=-33.3 azimuth_rad=-7.6188 elevation_rad=-5.8688 rcs_dbsm=22.0
//           snr_db=50.0 is_stationary=false
//           position=(2.632094495484701, -10.9846469104106, 4.968421361000493)

// v3: boundary/extreme raw values (max range field, all-zero everything else).
inline const std::vector<uint8_t> kSlotV3BoundaryExtremes = {0, 0, 63, 255, 128, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0};
// Expected: range_m=327.67 vel_mps=-83.3 azimuth_rad=-3.15 elevation_rad=-3.15 rcs_dbsm=-40.0
//           snr_db=0.0 is_stationary=true
//           position=(327.64683969187683, -2.754705385853436, 2.754802744793588)

// Header: timestamp=1, frame_id=7, radar_id=2, det_number=5.
inline const std::vector<uint8_t> kHeaderDetNumber5 = {0, 0, 0, 0, 0, 0, 0, 1, 0, 7, 8, 0, 160};

// Header: timestamp=2, frame_id=9, radar_id=1, det_number=0 (exercises the "expected_frames == 0 ->
// fall back to 1" edge case, since (0//3)+(1 if 0%3 else 0) == 0).
inline const std::vector<uint8_t> kHeaderDetNumber0 = {0, 0, 0, 0, 0, 0, 0, 2, 0, 9, 4, 0, 0};

// Header: timestamp=3, frame_id=11, radar_id=0, det_number=6 (exact multiple of 3 -- two full
// 3-slot body frames, no remainder frame).
inline const std::vector<uint8_t> kHeaderDetNumber6 = {0, 0, 0, 0, 0, 0, 0, 3, 0, 11, 0, 0, 192};

}  // namespace test_fixtures
}  // namespace radarcam
}  // namespace bev
